# Method 
Methods are functions (in that they perform computations) however, unlike functionality are attached to object.


In [28]:
type("kkkkk") #function

#'kkkk'.type () method

str

# Format method()

Format method is use in string to make very flexible change.

In [22]:
form = 'my name is {} and i am here for the data science training holding at {}'
form.format ('Precious', 'Yaba')

'my name is Precious and i am here for the data science training holding at Yaba'

In [19]:
form.format: ('Precious', 'Yaba')

In [23]:
form.format('Opeyemi', 'Coven Lab' )

'my name is Opeyemi and i am here for the data science training holding at Coven Lab'

In [32]:
var_1 = 'This is a new way to dance'

print(var_1.upper()) #convert everything to upper case

THIS IS A NEW WAY TO DANCE


In [26]:
var_1.split () #seperates a collection into several parts based on a 

['This', 'a', 'new', 'way', 'to', 'dance']

In [31]:
var_1.split ('a')


['This ', ' new w', 'y to d', 'nce']

In [33]:
var_1 = 'This is a new way to dance'

print(var_1.lower()) #convert everything to lower case


this is a new way to dance


In [34]:
var_1 = 'This is a new way to dance'

print(var_1.title()) #convert everything to title case

This Is A New Way To Dance


In [35]:
'my name is Kane'.split()



['my', 'name', 'is', 'Kane']

In [37]:
import numpy as np 
 
#numpy is a module in python used for numerical analysis

In [41]:
[5, 6, 7, 8, 9] *3

[5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]

In [39]:
np.array ([5,6,7,8,9]) *3

array([15, 18, 21, 24, 27])

In [42]:
np.sqrt([5,6,7,8,9,10])

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [44]:
8*5

40

in numpy you can do virtually all mathematical operations, it performs these operations on array. Thus in order to perform mathematical compution on collection of objects they have to be converted to arrays. 

In [46]:
a = np.array ([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [48]:
b = [4,5,6,7,8,9]
c = np.array(b)

In [49]:
print(b)
print(c)

[4, 5, 6, 7, 8, 9]
[4 5 6 7 8 9]


In [51]:
In [5]
c **2

array([16, 25, 36, 49, 64, 81], dtype=int32)

In [55]:
In [7]
#square root

np.sqrt(c)

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
       3.        ])

In [56]:
np.std(c) #standard deviation


1.707825127659933

In [58]:
np.sin(c) #calculate the sine

array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,
        0.41211849])

In [61]:
np.mean(c)   #mean

6.5

In [65]:
np.var(c)  #variance

2.9166666666666665

In [67]:
np.sum(c)

39

In [68]:
np.exp(c)

array([  54.59815003,  148.4131591 ,  403.42879349, 1096.63315843,
       2980.95798704, 8103.08392758])

# arange() funtion
This is a function that creates a range of numbers. it can take 1, 2 or 3 arguments. the first argument is start, the second is stop while the last is step. 

In [69]:

np.arange (5,10,2)

array([5, 7, 9])

In [71]:
np.arange (1,5)

array([1, 2, 3, 4])

In [74]:
np.arange (5)

array([0, 1, 2, 3, 4])

# linspace function
linspace function returns linearly spaced values between two numbers specified. it takes in two or three agruments. The first argument specifies the start while the second specifies the stop. the third on the other hand specifies the number of digits you want to return. By default it returns 100 linearly spaced numbers when the third agrument is not specified.

In [75]:
np.linspace(2,3,101)

array([2.  , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08, 2.09, 2.1 ,
       2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19, 2.2 , 2.21,
       2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 , 2.31, 2.32,
       2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41, 2.42, 2.43,
       2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.5 , 2.51, 2.52, 2.53, 2.54,
       2.55, 2.56, 2.57, 2.58, 2.59, 2.6 , 2.61, 2.62, 2.63, 2.64, 2.65,
       2.66, 2.67, 2.68, 2.69, 2.7 , 2.71, 2.72, 2.73, 2.74, 2.75, 2.76,
       2.77, 2.78, 2.79, 2.8 , 2.81, 2.82, 2.83, 2.84, 2.85, 2.86, 2.87,
       2.88, 2.89, 2.9 , 2.91, 2.92, 2.93, 2.94, 2.95, 2.96, 2.97, 2.98,
       2.99, 3.  ])

In [88]:
np.linspace(2,4)  #by default 50 linearly spaced values

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [89]:
np.linspace(2,4,5)

array([2. , 2.5, 3. , 3.5, 4. ])

# eye function
This function returns an identity matrix

In [93]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [94]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Pseudo-random numbers


In [99]:
import numpy.random as random        #randint produces random integers

random.randint(3,20,7)

array([ 4, 10, 17,  7, 14, 15, 19])

In [100]:
#returns an array of random numbers
random.rand(2,5)
#first and second arguments specify the number of rows while the third agrument specifies the number of columns

array([[0.84793634, 0.61446411, 0.00809393, 0.75908159, 0.46630336],
       [0.62996957, 0.71727967, 0.95804178, 0.03882254, 0.63966645]])

In [101]:
random.rand(3)

array([0.76316167, 0.23964985, 0.87809601])

In [102]:
np.random.randint(3,40,5)  

array([30,  6, 10, 16, 23])

In [103]:
random.seed(2)  #this is use to make constant your directory
random.randint(3,40,5)

array([18, 11, 25, 21, 14])

In [ ]:
a = 0
while a <= 8:
    a += 1
    if a % 4 == 1:
        continue
    print(a)